<?xml version="1.0" encoding="UTF-8"?>
<FIXML xsi:schemaLocation="http://www.finacle.com/fixml RetCustAdd.xsd"  xmlns="http://www.finacle.com/fixml"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header>
        <RequestHeader>
            <MessageKey>
                <RequestUUID>20250221131533</RequestUUID>
                <ServiceRequestId>RetCustAdd</ServiceRequestId>
                <ServiceRequestVersion>10.2</ServiceRequestVersion>
                <ChannelId>CRM</ChannelId>
                <LanguageId></LanguageId>
            </MessageKey>
            <RequestMessageInfo>
                <BankId>01</BankId>
                <TimeZone></TimeZone>
                <EntityId></EntityId>
                <EntityType></EntityType>
                <ArmCorrelationId></ArmCorrelationId>
                <MessageDateTime>04-05-2023T03:15:33.605</MessageDateTime>
            </RequestMessageInfo>
            <Security>
                <Token>
                    <PasswordToken>
                        <UserId></UserId>
                        <Password></Password>
                    </PasswordToken>
                </Token>
                <FICertToken></FICertToken>
                <RealUserLoginSessionId></RealUserLoginSessionId>
                <RealUser></RealUser>
                <RealUserPwd></RealUserPwd>
                <SSOTransferToken></SSOTransferToken>
            </Security>
        </RequestHeader>
    </Header>
    <Body></Body>
    <RetCustAddRequest>
        <RetCustAddRq>
            <CustDtls>
                <CustData>
                    <AddrDtls>
                        <PrefFormat>FREE_TEXT_FORMAT</PrefFormat>
                        <AddrCategory>Work</AddrCategory>
                        <AddrLine1>dummy address, DUMMY</AddrLine1>
                        <FreeTextLabel>Work</FreeTextLabel>
                        <City>AARA</City>
                        <State>TN</State>
                        <Country>IN</Country>
                        <PostalCode>123456</PostalCode>
                        <StartDt>2023-05-04T00:00:00.000</StartDt>
                        <PrefAddr>N</PrefAddr>
                        <HoldMailFlag>N</HoldMailFlag>
                    </AddrDtls>
                    <AddrDtls>
                        <PrefFormat>FREE_TEXT_FORMAT</PrefFormat>
                        <AddrCategory>Mailing</AddrCategory>
                        <AddrLine1>dummy address, DUMMY</AddrLine1>
                        <FreeTextLabel>Mailing</FreeTextLabel>
                        <City>AARA</City>
                        <State>TN</State>
                        <Country>IN</Country>
                        <PostalCode>123456</PostalCode>
                        <StartDt>2023-05-04T00:00:00.000</StartDt>
                        <PrefAddr>Y</PrefAddr>
                        <HoldMailFlag>N</HoldMailFlag>
                    </AddrDtls>
                    <Gender>M</Gender>
                    <Salutation>MR.</Salutation>
                    <LastName>WHITESTONE</LastName>
                    <ShortName>WS</ShortName>
                    <PrefName>WHITESTONE</PrefName>
                    <BirthDt>24</BirthDt>
                    <BirthMonth>03</BirthMonth>
                    <BirthYear>04</BirthYear>
                    <DateOfBirth>24-03-2004T00:00:00.000</DateOfBirth>
                    <IsMinor>N</IsMinor>
                    <MinorToMajorDt>24-03-2022T00:00:00.000</MinorToMajorDt>
                    <IsCustNRE>N</IsCustNRE>
                    <StaffFlag>N</StaffFlag>
                    <PrimarySolId>1001</PrimarySolId>
                    <SegmentationClass>001</SegmentationClass>
                    <SubSegment>001</SubSegment>
                    <TradeFinFlag>N</TradeFinFlag>
                    <Region>LKOCL</Region>
                    <TaxDeductionTable>T10</TaxDeductionTable>
                    <ccy>INR</ccy>
                    <purgeFlag>N</purgeFlag>
                    <enableCRMalert>N</enableCRMalert>
                    <IsEbankingEnabled>N</IsEbankingEnabled>
                    <Manager>UBSADMIN</Manager>
                    <RelationshipOpeningDt>2023-05-04T00:00:00.000</RelationshipOpeningDt>
                    <NativeLanguageCode>INFENG</NativeLanguageCode>
                    <Language>INFENG</Language>
                    <DefaultAddrType>Work</DefaultAddrType>
                    <PrefEmailType>HOMEEML</PrefEmailType>
                    <PrefPhoneType>COMMPH1</PrefPhoneType>
                    <PhoneEmailDtls>
                        <PhoneEmailType>COMMPH1</PhoneEmailType>
                        <PhoneNumCountryCode>91</PhoneNumCountryCode>
                        <PhoneNumLocalCode>1234567890</PhoneNumLocalCode>
                        <PhoneOrEmail>PHONE</PhoneOrEmail>
                        <PrefFlag>Y</PrefFlag>
                    </PhoneEmailDtls>
                </CustData>
            </CustDtls>
            <RelatedDtls>
                <DemographicData>
                    <Nationality>MIGR</Nationality>
                    <MaritalStatus>UNMAR</MaritalStatus>
                    <EmploymentStatus>Employed</EmploymentStatus>
                </DemographicData>
                <EntityDoctData>
                    <CountryOfIssue>IN</CountryOfIssue>
                    <DocCode>AADHA</DocCode>
                    <IssueDt>2023-05-04T00:00:00.000</IssueDt>
                    <TypeCode>AADHAR</TypeCode>
                    <EntityType>CIFRetCust</EntityType>
                    <PlaceOfIssue>AARA</PlaceOfIssue>
                    <ReferenceNum>123456789012</ReferenceNum>
                    <Type>CIF</Type>
                    <preferredUniqueId>Y</preferredUniqueId>
                </EntityDoctData>
                <PsychographicData>
                    <PsychographMiscData>
                        <StrText10>INR</StrText10>
                        <Type>CURRENCY</Type>
                    </PsychographMiscData>
                    <preferred_Locale>en_US</preferred_Locale>
                </PsychographicData>
            </RelatedDtls>
        </RetCustAddRq>
        <RetCustAdd_CustomData />
    </RetCustAddRequest>
</FIXML>